# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing

class Bone:
    index: int
    name: str
    parent_index: int
    scale: tuple[float, float, float]
    rotation: tuple[float, float, float, float]
    position: tuple[float, float, float]
    def __repr__(self) -> str:
        ...


class Keyframe:
    rotation: tuple[float, float, float, float]
    translation: tuple[float, float, float]
    scale: tuple[float, float, float]

class ModifiedFile:
    def __new__(cls,data:bytes, entry:PamtFileEntry, pamt_data:PamtData, package_group:str): ...
    ...

class PaaMetabin:
    path: str
    record_count: int
    file_size: int
    def records_as_list(self) -> typing.Any:
        ...


class PabgbTable:
    file_name: str
    row_count: int
    is_simple: bool
    row_size: int
    def rows_as_list(self) -> typing.Any:
        ...

    def get_row_by_hash(self, hash:int) -> typing.Optional[typing.Any]:
        ...


class PalocData:
    path: str
    entry_count: int
    def entries_as_list(self) -> typing.Any:
        ...

    def as_dict(self) -> typing.Any:
        ...

    def lookup(self, key:str) -> typing.Optional[str]:
        ...


class PamtData:
    path: str
    self_crc: int
    paz_count: int
    folder_prefix: str
    file_entries: list[PamtFileEntry]
    def find_entry(self, filename:str) -> typing.Optional[PamtFileEntry]:
        ...

    def __repr__(self) -> str:
        ...


class PamtFileEntry:
    path: str
    paz_file: str
    offset: int
    comp_size: int
    orig_size: int
    flags: int
    paz_index: int
    compressed: bool
    compression_type: int
    encrypted: bool
    record_offset: int
    def __repr__(self) -> str:
        ...


class ParsedAnimation:
    path: str
    frame_count: int
    bone_count: int
    fps: float
    metadata_tags: str
    is_character: bool
    def get_keyframe(self, frame:int, bone:int) -> typing.Any:
        r"""
        keyframes[frame_idx][bone_idx] -> Keyframe
        """
        ...


class ParsedHavok:
    path: str
    sdk_version: str
    has_skeleton: bool
    has_animation: bool
    has_physics: bool
    has_ragdoll: bool
    has_cloth: bool
    has_mesh_shape: bool
    binds_to_mesh_topology: bool
    class_names: list[str]
    shape_types: list[str]

class ParsedMesh:
    path: str
    format: str
    has_uvs: bool
    total_vertices: int
    total_faces: int
    bbox_min: tuple[float, float, float]
    bbox_max: tuple[float, float, float]
    submeshes: list[SubMesh]

class ParsedNavmesh:
    path: str
    cell_count: int
    file_size: int
    def cells_as_list(self) -> typing.Any:
        ...


class ParsedPac:
    path: str
    has_uvs: bool
    has_bones: bool
    total_vertices: int
    total_faces: int
    bbox_min: tuple[float, float, float]
    bbox_max: tuple[float, float, float]
    submeshes: list[SubMesh]

class ParsedPrefab:
    path: str
    file_hash_1: int
    file_hash_2: int
    component_count: int
    def strings_as_list(self) -> typing.Any:
        ...

    def file_refs(self) -> list[str]:
        ...


class RepackEngine:
    def __new__(cls,packages_path,backup_dir = ...): ...
    def repack(self, modified_files,papgt_path,create_backup = ...) -> RepackResult:
        ...


class RepackResult:
    success: bool
    files_repacked: int
    paz_crc: int
    pamt_crc: int
    papgt_crc: int
    backup_dir: str
    errors: list[str]

class Skeleton:
    path: str
    bones: list[Bone]
    bone_count: int

class SubMesh:
    name: str
    material: str
    texture: str
    vertex_count: int
    face_count: int
    vertices: list[tuple[float, float, float]]
    uvs: list[tuple[float, float]]
    normals: list[tuple[float, float, float]]
    faces: list[tuple[int, int, int]]

class VfsManager:
    packages_path: str
    def __new__(cls,packages_path:str): ...
    def load_all_groups(self) -> None:
        ...

    def load_group(self, group_dir:str) -> None:
        ...

    def list_groups(self) -> list[str]:
        ...

    def lookup(self, path:str) -> typing.Optional[PamtFileEntry]:
        ...

    def read_entry(self, entry:PamtFileEntry) -> bytes:
        ...

    def search(self, query:str) -> list[PamtFileEntry]:
        ...

    def list_dir(self, path:str) -> list[str]:
        ...

    def reload(self) -> None:
        ...

    def invalidate_group(self, group_dir:str) -> None:
        ...


def decompress(data,orig_size,compression_type) -> typing.Any:
    ...

def decrypt(data:bytes,filename:str) -> typing.Any:
    ...

def encrypt(data:bytes,filename:str) -> typing.Any:
    ...

def is_encrypted(path:str) -> bool:
    ...

def lz4_compress(data:bytes) -> typing.Any:
    ...

def lz4_decompress(data:bytes,orig_size:int) -> typing.Any:
    ...

def pa_checksum(data:bytes) -> int:
    ...

def parse_hkx(data:bytes,filename:typing.Optional[str]) -> ParsedHavok:
    ...

def parse_nav(data:bytes,filename:typing.Optional[str]) -> ParsedNavmesh:
    ...

def parse_paa(data:bytes,filename:typing.Optional[str]) -> ParsedAnimation:
    ...

def parse_paa_metabin(data:bytes,filename:typing.Optional[str]) -> PaaMetabin:
    ...

def parse_pab(data:bytes,filename:typing.Optional[str]) -> Skeleton:
    ...

def parse_pabgb(pabgh_data:bytes,pabgb_data:bytes,filename:typing.Optional[str]) -> PabgbTable:
    ...

def parse_pac(data:bytes,filename:typing.Optional[str]) -> ParsedPac:
    ...

def parse_paloc(data:bytes,filename:typing.Optional[str]) -> PalocData:
    ...

def parse_pam(data:bytes,filename:typing.Optional[str]) -> ParsedMesh:
    ...

def parse_pamlod(data:bytes,filename:typing.Optional[str]) -> ParsedMesh:
    ...

def parse_pamt(pamt_path:str,paz_dir:typing.Optional[str]) -> PamtData:
    ...

def parse_prefab(data:bytes,filename:typing.Optional[str]) -> ParsedPrefab:
    ...

def verify_chain(pamt_path:str,papgt_path:str) -> bool:
    ...

def zlib_compress(data:bytes) -> typing.Any:
    ...

def zlib_decompress(data:bytes) -> typing.Any:
    ...

